export const surpriseMePrompts = [
  "Generate an image of a towering treehouse nestled in a dense forest, with a winding staircase leading up to its entrance.",
"Create an image of a neon-lit cityscape with towering skyscrapers, bustling streets, and flying cars weaving in and out of the traffic.",
"Generate an image of a majestic dragon perched atop a snowy mountaintop, with its wings spread wide and fire breathing from its mouth.",
"Create an image of an enchanted garden with lush greenery, sparkling fountains, and winding paths leading to hidden nooks and crannies.",
"Generate an image of a futuristic laboratory with glowing vials, intricate machinery, and scientists working diligently on cutting-edge experiments.",
"Create an image of an otherworldly underwater kingdom with iridescent sea creatures, vibrant coral reefs, and shimmering mermaids.",
"Generate an image of a cozy cabin in the woods with a crackling fire, comfortable armchairs, and shelves lined with books.",
"Create an image of a bustling marketplace with colorful stalls, exotic foods, and merchants haggling with customers.",
"Generate an image of a whimsical circus with clowns, acrobats, and a big top tent filled with magic and wonder.",
"Create an image of a far-off planet with strange landscapes, alien creatures, and advanced technology beyond our imagination.",
"Generate an image of a tranquil garden with a pond filled with koi fish, blooming cherry blossom trees, and a serene pagoda in the background.",
"Create an image of a mystical forest with a hidden waterfall, ancient ruins, and glowing mushrooms dotting the forest floor.",
"Generate an image of a retro diner with neon signs, checkerboard floors, and a jukebox playing classic tunes.",
"Create an image of a grand castle with towering turrets, a moat filled with water, and a drawbridge leading to the entrance.",
"Generate an image of a busy airport with planes taking off and landing, bustling crowds, and luggage carts zipping by.",
"A majestic elephant standing on top of a mountain peak with a waterfall in the background.",
"An enchanted forest with glowing trees and a magical castle in the distance.",
"A futuristic cityscape with hovering vehicles and neon lights.",
"A cozy library with shelves filled with books and a fireplace crackling in the background.",
"A serene beach with crystal clear water and palm trees swaying in the breeze.",
"A fantastical garden with floating flowers and a hidden fairy door.",
"A whimsical tea party with a giant teapot and oversized teacups.",
"A space station orbiting a distant planet with a view of the galaxy.",
"A vintage travel poster featuring a train winding through a mountain range.",
"A magical portal leading to a hidden world filled with mythical creatures.",
"An underwater city with colorful coral and schools of fish swimming by.",
"A bustling market with colorful stalls and vendors selling exotic goods.",
"A fairytale castle perched on a cliff overlooking the ocean.",
"A cozy cabin in the woods with a roaring fire and a view of the stars.",
"A rainbow-colored hot air balloon floating over a rolling landscape.",
"A haunted mansion with creaky floorboards and cobweb-covered furniture.",
"A modern art museum with abstract sculptures and colorful paintings.",
"A futuristic spaceship with sleek lines and cutting-edge technology.",
"A quaint village nestled in the hills with winding cobblestone streets.",
"A towering lighthouse on a stormy night with crashing waves below.",
"A high-speed train racing through a snowy landscape.",
"A mystical forest with glowing mushrooms and hidden creatures.",
"An ancient temple in the jungle with intricate carvings and hidden passageways.",
"A tranquil garden with a koi pond and a stone bridge.",
"A futuristic laboratory with advanced technology and glowing screens.",
"A steampunk city with mechanical devices and clockwork machinery.",
"A medieval castle with a drawbridge and knights in armor.",
"A desert oasis with palm trees and a shimmering pool.",
"A winter wonderland with snow-covered trees and a frozen lake.",
"A carnival with brightly colored tents and attractions.",
"A safari adventure with wild animals and rugged terrain.",
"A retro diner with a jukebox and neon signs.",
"A European cityscape with ornate architecture and winding alleys.",
"A cozy coffee shop with plush chairs and a fireplace.",
"A futuristic sports stadium with high-tech equipment and holographic displays.",
"A rustic cabin in the mountains with a babbling brook nearby.",
"A futuristic city with flying cars and towering skyscrapers.",
"A spooky graveyard with fog and eerie lighting.",
"A tropical island with white sand beaches and crystal clear water.",
"A glamorous Hollywood movie premiere with red carpets and flashing cameras.",
"An underwater exploration vehicle discovering deep sea creatures.",
"A bustling kitchen with chefs preparing a feast.",
"A rocky canyon with a river flowing through it.",
"A futuristic battle arena with advanced robots fighting.",
"A mysterious hidden cave with glittering gems and treasures.",
"A snowy ski resort with a roaring fire in the lodge.",
"A lush vineyard with grapevines stretching out in all directions.",
"A futuristic spaceship battle in deep space.",
"An ancient pyramid with secret chambers and hidden treasures.",
"A bustling train station with steam engines and passengers boarding.",
"A futuristic city with sleek, geometric architecture and minimalist design.",
"A dark alleyway with neon lights and street vendors.",
"A colorful coral reef",
"A lone traveler walking along a deserted road, with nothing but fields and forests stretching out on either side. The sky above is a brilliant shade of blue, dotted with fluffy white clouds. The traveler carries a heavy backpack, and wears sturdy boots and a wide-brimmed hat to shield them from the sun. The traveler had been on the road for days, walking with no particular destination in mind. They had left their old life behind, seeking adventure and a sense of purpose. Though they had encountered a few kind strangers and interesting sights along the way, most of their journey had been spent in solitude. As they walked, they reflected on their past and contemplated their future, wondering what lay ahead on this path they had chosen.",
"A group of friends hiking up a steep mountain trail, with breathtaking views of valleys and peaks in the distance. They are all wearing hiking boots and backpacks, and their faces are flushed with exertion. One member of the group pauses to take a photo with a camera, capturing the stunning scenery. The friends had planned this hike for months, eager to escape the stresses of their daily lives and reconnect with nature. As they climbed higher, they encouraged each other and shared stories of their experiences. They marveled at the beauty of the landscape around them, feeling small and insignificant in the face of such grandeur. At the summit, they celebrated their accomplishment with high-fives and a group photo, feeling renewed and invigorated. ",
"A family on a road trip, driving along a winding highway with mountains on one side and the ocean on the other. The car is filled with laughter and chatter, as the parents and children take turns picking songs to play on the stereo. They stop at a lookout point to take in the view, and the parents snap photos of the kids posing in front of the scenery. The family had planned this trip for months, carefully mapping out their route and choosing activities to keep everyone entertained. They had packed snacks and games, and had even created a playlist of songs that everyone could enjoy. As they drove, they sang along and pointed out interesting sights along the way. They were creating memories that would last a lifetime, and were grateful for the chance to bond as a family. ",
"A lone sailor on a sailboat, navigating through a stormy sea with fierce winds and towering waves. The boat rocks and creaks, and the sailor grips the wheel tightly, focused on staying the course. Lightning flashes overhead, illuminating the dark clouds and churning water. The sailor had embarked on this journey to prove their courage and skill, but had not anticipated such treacherous conditions. They were filled with fear and doubt, wondering if they had made a mistake in setting out on this voyage. But they knew they had no choice but to press on, relying on their training and instincts to guide them. As the storm raged on, the sailor drew strength from their determination and perseverance, determined to make it through to calmer waters. "
];
